name: A_repo
on:
  workflow_dispatch:
     inputs:
      workflow_02:
        description: 'Ù‹resusable-workflow-caller which will be triggered'
        required: true
        default: ':resusable-workflow-caller'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':userName'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: ':repoName' 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          
            curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer "${{ secrets.ACTIONSKEY}}" " \
            https://api.github.com/repos/:userName/:repoName/actions/workflows/:resusable-workflow-caller/dispatches \
            -d '{"ref":"main","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'
      - uses: actions/checkout@v3
