name: differnt  version OS install
on:
  workflow_dispatch: {}
jobs:
  build_matrix: 
     strategy: 
        matrix:
             os: [ ubuntu-latest, ubuntu-latest ]
             version: [ 10,12,14 ]
     runs-on: ${{ matrix.os }}
     steps:
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.version }}
        
